List<List<String>> data = [
  ["I am going home", "domum eō."],
  ["I was going home", "domum ībam."],
  ["I will be going home", "domum ībō."],
  ["You are going home", "domum īs."],
  ["You were going home", "domum ībās."],
  ["You will be going home", "domum ībīs."],
  ["He is going home", "domum it."],
  ["He was going home", "domum ībat."],
  ["He will be going home", "domum ībit."],
  ["She is going home", "domum it."],
  ["She was going home", "domum ībat."],
  ["She will be going home", "domum ībit."],
  ["It is going home", "domum it."],
  ["It was going home", "domum ībat."],
  ["It will be going home", "domum ībit."],
  ["We are going home", "domum īmus."],
  ["We were going home", "domum ībāmus."],
  ["We will be going home", "domum ībimus."],
  ["You all are going home", "domum ītis."],
  ["You all were going home", "domum ībātis."],
  ["You all will be going home", "domum ībitis."],
  ["They are going home", "domum eunt."],
  ["They were going home", "domum ībant."],
  ["They will be going home", "domum ībunt."],
  ["Romans go home!", "Rōmānī īte domum"]
];

